#!/bin/bash
# build-project --- Create HTML files from markdown files in docs directory.
set -e

cd $PROJ_DIR

# rm -rf docs
mkdir -p docs/lessons

for file in README.md lessons/*.md
do
    target="docs/${file%.md}.html"
    echo Building $target
    cat assets/jekyll-header.html > $target
    markdown-it $file >> docs/${file%.md}.html
    cat assets/jekyll-footer.html >> $target
done

mkdir -p docs/styles && cp assets/style.css docs/styles
mkdir -p docs/scripts && cp scripts/*.js docs/scripts

tree docs
